openapi: 3.0.1
info:
  title: File Upload API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload files with nested objects
      operationId: uploadFiles
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                  example: 123
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                nestedObjs:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                        example: key1
                      value:
                        type: string
                        example: value1
      responses:
        '200':
          description: Successful upload
        '400':
          description: Invalid input
        '500':
          description: Server error
